name: Deploy VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Azure Credentials JSON File
        id: read_credentials
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
          CLIENT_ID=$(jq -r '.clientId' azure_credentials.json)
          CLIENT_SECRET=$(jq -r '.clientSecret' azure_credentials.json)
          TENANT_ID=$(jq -r '.tenantId' azure_credentials.json)
          echo "::set-output name=CLIENT_ID::$CLIENT_ID"
          echo "::set-output name=CLIENT_SECRET::$CLIENT_SECRET"
          echo "::set-output name=TENANT_ID::$TENANT_ID"

      - name: Log in to Azure
        run: az login --service-principal -u ${{ steps.read_credentials.outputs.CLIENT_ID }} -p ${{ steps.read_credentials.outputs.CLIENT_SECRET }} --tenant ${{ steps.read_credentials.outputs.TENANT_ID }}

      - name: Deploy VM using Bicep
        run: |
          az deployment group create \
            --resource-group azure-training1 \
            --template-file main.bicep \
            --parameters @parameters.json
